<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="AuthorizationQueryService" targetNamespace="http://bis/dataservices/authorizationquery/v1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
                  xmlns:wsa10="http://www.w3.org/2005/08/addressing"
                  xmlns:tns="http://bis/dataservices/authorizationquery/v1"
                  xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
                  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:id="http://x-road.eu/xsd/identifiers">
    <wsdl:types>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://x-road.eu/xsd/identifiers"
                   xmlns="http://x-road.eu/xsd/identifiers" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:complexType name="XRoadIdentifierType">
                <xs:annotation>
                    <xs:documentation>
                        Globally unique identifier in the X-Road system.
                        Identifier consists of object type specifier and list of
                        hierarchical codes (starting with code that identifiers
                        the X-Road instance).
                    </xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element minOccurs="0" ref="xRoadInstance"/>
                    <xs:element minOccurs="0" ref="memberClass"/>
                    <xs:element minOccurs="0" ref="memberCode"/>
                    <xs:element minOccurs="0" ref="subsystemCode"/>
                    <xs:element minOccurs="0" ref="groupCode"/>
                    <xs:element minOccurs="0" ref="serviceCode"/>
                    <xs:element minOccurs="0" ref="serviceVersion"/>
                    <xs:element minOccurs="0" ref="securityCategoryCode"/>
                    <xs:element minOccurs="0" ref="serverCode"/>
                </xs:sequence>
                <xs:attribute ref="objectType" use="required"/>
            </xs:complexType>
            <xs:simpleType name="XRoadObjectType">
                <xs:annotation>
                    <xs:documentation>
                        Enumeration for X-Road identifier
                        types.
                    </xs:documentation>
                </xs:annotation>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="MEMBER"/>
                    <xs:enumeration value="SUBSYSTEM"/>
                    <xs:enumeration value="SERVER"/>
                    <xs:enumeration value="GLOBALGROUP"/>
                    <xs:enumeration value="LOCALGROUP"/>
                    <xs:enumeration value="SECURITYCATEGORY"/>
                    <xs:enumeration value="SERVICE"/>
                    <xs:enumeration value="CENTRALSERVICE"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="xRoadInstance" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Identifies the X-Road instance. This field is
                        applicable to all identifier types.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="memberClass" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Type of the member (company, government
                        institution, private person, etc.)
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="memberCode" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Code that uniquely identifies a member of given
                        member type.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="subsystemCode" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Code that uniquely identifies a subsystem of
                        given X-Road member.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="groupCode" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Code that uniquely identifies a global group in
                        given X-Road instance.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="serviceCode" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Code that uniquely identifies a service offered by
                        given X-Road member or subsystem.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="serviceVersion" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Version of the service.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="securityCategoryCode" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Code that uniquely identifies security category in
                        a given X-Road instance.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="serverCode" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        Code that uniquely identifies security server
                        offered by a given X-Road member or
                        subsystem.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:attribute name="objectType" type="XRoadObjectType"/>
            <xs:complexType name="XRoadClientIdentifierType">
                <xs:complexContent>
                    <xs:restriction base="XRoadIdentifierType">
                        <xs:sequence>
                            <xs:element ref="xRoadInstance"/>
                            <xs:element ref="memberClass"/>
                            <xs:element ref="memberCode"/>
                            <xs:element minOccurs="0" ref="subsystemCode"/>
                        </xs:sequence>
                        <xs:attribute ref="objectType" use="required"/>
                    </xs:restriction>
                </xs:complexContent>
            </xs:complexType>
            <xs:complexType name="XRoadServiceIdentifierType">
                <xs:complexContent>
                    <xs:restriction base="XRoadIdentifierType">
                        <xs:sequence>
                            <xs:element ref="xRoadInstance"/>
                            <xs:element ref="memberClass"/>
                            <xs:element ref="memberCode"/>
                            <xs:element minOccurs="0" ref="subsystemCode"/>
                            <xs:element ref="serviceCode"/>
                            <xs:element minOccurs="0" ref="serviceVersion"/>
                        </xs:sequence>
                        <xs:attribute ref="objectType" use="required" fixed="SERVICE"/>
                    </xs:restriction>
                </xs:complexContent>
            </xs:complexType>
            <xs:complexType name="XRoadSecurityCategoryIdentifierType">
                <xs:complexContent>
                    <xs:restriction base="XRoadIdentifierType">
                        <xs:sequence>
                            <xs:element ref="xRoadInstance"/>
                            <xs:element ref="securityCategoryCode"/>
                        </xs:sequence>
                        <xs:attribute ref="objectType" use="required" fixed="SECURITYCATEGORY"/>
                    </xs:restriction>
                </xs:complexContent>
            </xs:complexType>
            <xs:complexType name="XRoadCentralServiceIdentifierType">
                <xs:complexContent>
                    <xs:restriction base="XRoadIdentifierType">
                        <xs:sequence>
                            <xs:element ref="xRoadInstance"/>
                            <xs:element ref="serviceCode"/>
                        </xs:sequence>
                        <xs:attribute ref="objectType" use="required" fixed="CENTRALSERVICE"/>
                    </xs:restriction>
                </xs:complexContent>
            </xs:complexType>
            <xs:complexType name="XRoadSecurityServerIdentifierType">
                <xs:complexContent>
                    <xs:restriction base="XRoadIdentifierType">
                        <xs:sequence>
                            <xs:element ref="xRoadInstance"/>
                            <xs:element ref="memberClass"/>
                            <xs:element ref="memberCode"/>
                            <xs:element ref="serverCode"/>
                        </xs:sequence>
                        <xs:attribute ref="objectType" use="required" fixed="SERVER"/>
                    </xs:restriction>
                </xs:complexContent>
            </xs:complexType>
            <xs:complexType name="XRoadGlobalGroupIdentifierType">
                <xs:complexContent>
                    <xs:restriction base="XRoadIdentifierType">
                        <xs:sequence>
                            <xs:element ref="xRoadInstance"/>
                            <xs:element ref="groupCode"/>
                        </xs:sequence>
                        <xs:attribute ref="objectType" use="required" fixed="GLOBALGROUP"/>
                    </xs:restriction>
                </xs:complexContent>
            </xs:complexType>
            <xs:complexType name="XRoadLocalGroupIdentifierType">
                <xs:complexContent>
                    <xs:restriction base="XRoadIdentifierType">
                        <xs:sequence>
                            <xs:element ref="groupCode"/>
                        </xs:sequence>
                        <xs:attribute ref="objectType" use="required" fixed="LOCALGROUP"/>
                    </xs:restriction>
                </xs:complexContent>
            </xs:complexType>
        </xs:schema>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://x-road.eu/xsd/xroad.xsd"
                   xmlns="http://x-road.eu/xsd/xroad.xsd" xmlns:id="http://x-road.eu/xsd/identifiers"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:import namespace="http://www.w3.org/XML/1998/namespace"
                       schemaLocation="http://www.w3.org/2001/xml.xsd"/>
            <xs:import id="id" namespace="http://x-road.eu/xsd/identifiers"/><!-- This types are required for .NET/WSDL.exe proxy generation, types replace xs:string -->
            <xs:simpleType name="idType">
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
            <xs:simpleType name="userIdType">
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
            <xs:simpleType name="issueType">
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
            <xs:simpleType name="protocolVersionType">
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
            <xs:simpleType name="versionType">
                <xs:restriction base="xs:string"/>
            </xs:simpleType><!-- Header elements -->
            <xs:element name="client" type="id:XRoadClientIdentifierType">
                <xs:annotation>
                    <xs:documentation>Identies service client</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="service" type="id:XRoadServiceIdentifierType">
                <xs:annotation>
                    <xs:documentation>
                        Identies the service
                        that is invoked by the request
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="centralService" type="id:XRoadCentralServiceIdentifierType">
                <xs:annotation>
                    <xs:documentation>
                        Identies the central service
                        that is invoked by the request.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="id" type="idType">
                <xs:annotation>
                    <xs:documentation>
                        Unique identier
                        for this message
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="userId" type="userIdType">
                <xs:annotation>
                    <xs:documentation>
                        User whose action initiated
                        the request
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="requestHash">
                <xs:annotation>
                    <xs:documentation>
                        Base64 encoded hash of
                        the SOAP request message
                    </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="algorithmId" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>
                                        Identies hash algorithm
                                        that was used to calculate the value
                                        of the requestHash field.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="issue" type="issueType">
                <xs:annotation>
                    <xs:documentation>
                        Identies received application, issue or document
                        that was the cause of the service request.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="protocolVersion" type="protocolVersionType">
                <xs:annotation>
                    <xs:documentation>X-Road message protocol version</xs:documentation>
                </xs:annotation>
            </xs:element><!-- Elements describing other elements and operations-->
            <xs:element name="version" type="versionType">
                <xs:annotation>
                    <xs:documentation>Version of the service</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="title">
                <xs:annotation>
                    <xs:documentation>Title of the service</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute default="en" ref="xml:lang"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="notes">
                <xs:annotation>
                    <xs:documentation>Notes for user</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" default="en"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="techNotes">
                <xs:annotation>
                    <xs:documentation>Notes for technical stuff</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" default="en"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://bis/dataservices/authorizationquery/v1"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="GetCompanyAuthorizationData">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="request" type="tns:XrdGetCompanyAuthorizationDataRequest"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:complexType name="AuthorizationQuery">
                <xs:sequence>
                    <xs:element minOccurs="0" name="SocialSecurityNumber" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="AuthorizationQuery" nillable="true" type="tns:AuthorizationQuery"/>
            <xs:element name="GetCompanyAuthorizationDataResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="request" type="tns:XrdGetCompanyAuthorizationDataRequest"/>
                        <xs:element name="response" type="tns:XrdGetCompanyAuthorizationDataResponse"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:complexType name="AuthorizationQueryResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="BusinessId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="TradeName" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="AuthorizationQueryResponse" nillable="true" type="tns:AuthorizationQueryResponse"/>
            <xs:complexType name="SocialSecurityNumberFault">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Descriptions" nillable="true" type="tns:ArrayOfErrorDescription"/>
                    <xs:element minOccurs="0" name="RawDetail" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="SocialSecurityNumberFault" nillable="true" type="tns:SocialSecurityNumberFault"/>
            <xs:complexType name="ArrayOfErrorDescription">
                <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="ErrorDescription" nillable="true"
                                type="tns:ErrorDescription"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="ArrayOfErrorDescription" nillable="true" type="tns:ArrayOfErrorDescription"/>
            <xs:complexType name="ErrorDescription">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Language" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Description" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="ErrorDescription" nillable="true" type="tns:ErrorDescription"/>
            <xs:complexType name="CompanyNotFoundFault">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Descriptions" nillable="true" type="tns:ArrayOfErrorDescription"/>
                    <xs:element minOccurs="0" name="RawDetail" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="CompanyNotFoundFault" nillable="true" type="tns:CompanyNotFoundFault"/>
            <xs:complexType name="QueryFailedFault">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Descriptions" nillable="true" type="tns:ArrayOfErrorDescription"/>
                    <xs:element minOccurs="0" name="RawDetail" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="QueryFailedFault" nillable="true" type="tns:QueryFailedFault"/>
            <xs:complexType name="ServiceOfflineFault">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Descriptions" nillable="true" type="tns:ArrayOfErrorDescription"/>
                    <xs:element minOccurs="0" name="RawDetail" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="ServiceOfflineFault" nillable="true" type="tns:ServiceOfflineFault"/>
            <xs:complexType name="XrdGetCompanyAuthorizationDataRequest">
                <xs:sequence>
                    <xs:element minOccurs="0" name="authorizationQuery" nillable="true" type="tns:AuthorizationQuery"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="XrdGetCompanyAuthorizationDataResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="GetCompanyAuthorizationDataResult" nillable="true"
                                type="tns:AuthorizationQueryResponse"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified"
                   targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="XRoadSoapHeader" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xrd="http://x-road.eu/xsd/xroad.xsd">
        <wsdl:part name="client" element="xrd:client"/>
        <wsdl:part name="service" element="xrd:service"/>
        <wsdl:part name="id" element="xrd:id"/>
        <wsdl:part name="userId" element="xrd:userId"/>
        <wsdl:part name="requestHash" element="xrd:requestHash"/>
        <wsdl:part name="issue" element="xrd:issue"/>
        <wsdl:part name="protocolVersion" element="xrd:protocolVersion"/>
    </wsdl:message>
    <wsdl:message name="AuthorizationQueryService_GetCompanyAuthorizationData_InputMessage">
        <wsdl:part name="parameters" element="tns:GetCompanyAuthorizationData"/>
    </wsdl:message>
    <wsdl:message name="AuthorizationQueryService_GetCompanyAuthorizationData_OutputMessage">
        <wsdl:part name="parameters" element="tns:GetCompanyAuthorizationDataResponse"/>
    </wsdl:message>
    <wsdl:message
            name="AuthorizationQueryService_GetCompanyAuthorizationData_SocialSecurityNumberFaultFault_FaultMessage">
        <wsdl:part name="detail" element="tns:SocialSecurityNumberFault"/>
    </wsdl:message>
    <wsdl:message name="AuthorizationQueryService_GetCompanyAuthorizationData_CompanyNotFoundFaultFault_FaultMessage">
        <wsdl:part name="detail" element="tns:CompanyNotFoundFault"/>
    </wsdl:message>
    <wsdl:message name="AuthorizationQueryService_GetCompanyAuthorizationData_QueryFailedFaultFault_FaultMessage">
        <wsdl:part name="detail" element="tns:QueryFailedFault"/>
    </wsdl:message>
    <wsdl:message name="AuthorizationQueryService_GetCompanyAuthorizationData_ServiceOfflineFaultFault_FaultMessage">
        <wsdl:part name="detail" element="tns:ServiceOfflineFault"/>
    </wsdl:message>
    <wsdl:portType name="AuthorizationQueryService">
        <wsdl:operation name="GetCompanyAuthorizationData">
            <wsdl:input wsaw:Action="http://bis/dataservices/authorizationquery/v1/GetCompanyAuthorizationData"
                        message="tns:AuthorizationQueryService_GetCompanyAuthorizationData_InputMessage"/>
            <wsdl:output wsaw:Action="http://bis/dataservices/authorizationquery/v1/GetCompanyAuthorizationDataResponse"
                         message="tns:AuthorizationQueryService_GetCompanyAuthorizationData_OutputMessage"/>
            <wsdl:fault
                    wsaw:Action="http://bis/dataservices/authorizationquery/v1/GetCompanyAuthorizationDataSocialSecurityNumberFaultFault"
                    name="SocialSecurityNumberFaultFault"
                    message="tns:AuthorizationQueryService_GetCompanyAuthorizationData_SocialSecurityNumberFaultFault_FaultMessage"/>
            <wsdl:fault
                    wsaw:Action="http://bis/dataservices/authorizationquery/v1/GetCompanyAuthorizationDataCompanyNotFoundFaultFault"
                    name="CompanyNotFoundFaultFault"
                    message="tns:AuthorizationQueryService_GetCompanyAuthorizationData_CompanyNotFoundFaultFault_FaultMessage"/>
            <wsdl:fault
                    wsaw:Action="http://bis/dataservices/authorizationquery/v1/GetCompanyAuthorizationDataQueryFailedFaultFault"
                    name="QueryFailedFaultFault"
                    message="tns:AuthorizationQueryService_GetCompanyAuthorizationData_QueryFailedFaultFault_FaultMessage"/>
            <wsdl:fault
                    wsaw:Action="http://bis/dataservices/authorizationquery/v1/GetCompanyAuthorizationDataServiceOfflineFaultFault"
                    name="ServiceOfflineFaultFault"
                    message="tns:AuthorizationQueryService_GetCompanyAuthorizationData_ServiceOfflineFaultFault_FaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="AuthorizationQueryServiceEndpoint" type="tns:AuthorizationQueryService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetCompanyAuthorizationData">
            <soap:operation soapAction="" style="document"/>
            <id:version>v1</id:version>
            <wsdl:input>
                <soap:body use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="client" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="service" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="id" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="userId" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="issue" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="protocolVersion" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="client" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="service" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="id" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="userId" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="requestHash" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="issue" use="literal"/>
                <soap:header message="tns:XRoadSoapHeader" part="protocolVersion" use="literal"/>
            </wsdl:output>
            <wsdl:fault name="SocialSecurityNumberFaultFault">
                <soap:fault use="literal" name="SocialSecurityNumberFaultFault" namespace=""/>
            </wsdl:fault>
            <wsdl:fault name="CompanyNotFoundFaultFault">
                <soap:fault use="literal" name="CompanyNotFoundFaultFault" namespace=""/>
            </wsdl:fault>
            <wsdl:fault name="QueryFailedFaultFault">
                <soap:fault use="literal" name="QueryFailedFaultFault" namespace=""/>
            </wsdl:fault>
            <wsdl:fault name="ServiceOfflineFaultFault">
                <soap:fault use="literal" name="ServiceOfflineFaultFault" namespace=""/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AuthorizationQueryService">
        <wsdl:port name="AuthorizationQueryServiceEndpoint" binding="tns:AuthorizationQueryServiceEndpoint">
            <soap:address
                    location="https://dataservices.ytj.local:8091/AuthorizationQuery/AuthorizationQueryServiceAdapter.ashx"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>